import { E4 } from "./e4"

export const e4: E4[]=[
    {
        name: 'Alekhines',
        description: 'The Alekhines Defence is a defense when white plays 1.e4 as his first move. Black attacks the e4 pawn with his knight, encouraging White to advance his central pawns to chase the Knight away ',
        image0: './assets/E4 opening/alekhines_defense/alekhine_defense.jpg',
        image1: './assets/E4 opening/alekhines_defense/Alek_startingPosition.jpg',
        image2: './assets/E4 opening/alekhines_defense/Alek_Wmv1.jpg',
        image3: './assets/E4 opening/alekhines_defense/Alek_Bmv1.jpg',
        image4: './assets/E4 opening/alekhines_defense/Alek_Wmv2.jpg',
        image5: './assets/E4 opening/alekhines_defense/Alek_Bmv2.jpg',
        image6: './assets/E4 opening/alekhines_defense/Alek_Wmv3.jpg',
        image7: './assets/E4 opening/alekhines_defense/Alek_Bmv3.jpg',
        image8: './assets/E4 opening/alekhines_defense/Alek_Wmv4.jpg',
        image9: './assets/E4 opening/alekhines_defense/Alek_Bmv4.jpg',
        image10: './assets/E4 opening/alekhines_defense/Alek_Wmv5.jpg',
        image11: './assets/E4 opening/alekhines_defense/Alek_Bmv5.jpg',
        description2: 'after the exchange of queens, black now has a huge advantage because of whites 3 weak pawns in the center and the king lossing the right to castle',
        image12: './assets/E4 opening/alekhines_defense/alekhine_defense.jpg'
        
    },
    {
        name: 'Caro-kann',
        description: ' ',
        image0: './assets/E4 opening/Caro-kann/ckblack_mv5.jpg',
        image1: './assets/E4 opening/Caro-kann/ckstartng_position.jpg',
        image2: './assets/E4 opening/Caro-kann/ckwhite_mv1.jpg',
        image3: './assets/E4 opening/Caro-kann/ckblack_mv1.jpg',
        image4: './assets/E4 opening/Caro-kann/ckwhite_mv2.jpg',
        image5: './assets/E4 opening/Caro-kann/ckblack_mv2.jpg',
        image6: './assets/E4 opening/Caro-kann/ckwhite_mv3.jpg',
        image7: './assets/E4 opening/Caro-kann/ckblack_mv3.jpg',
        image8: './assets/E4 opening/Caro-kann/ckwhite_mv4.jpg',
        image9:  './assets/E4 opening/Caro-kann/ckblack_mv4.jpg',
        image10: './assets/E4 opening/Caro-kann/ckwhite_mv5.jpg',
        image11: './assets/E4 opening/Caro-kann/ckblack_mv5.jpg',
        description2:'',
        image12: './assets/E4 opening/Caro-kann/ckblack_mv5.jpg'
        
    },
    {
        name: 'French Defense',
        description: ' ',
        image0: './assets/E4 opening/French Defense/Fblackmv5.jpg',
        image1: './assets/E4 opening/French Defense/fstartng_position.jpg',
        image2: './assets/E4 opening/French Defense/Fwhitemv1.jpg',
        image3: './assets/E4 opening/French Defense/Fblackmv1.jpg',
        image4: './assets/E4 opening/French Defense/Fwhitemv2.jpg',
        image5: './assets/E4 opening/French Defense/Fblackmv2.jpg',
        image6: './assets/E4 opening/French Defense/Fwhitemv3.jpg',
        image7: './assets/E4 opening/French Defense/Fblackmv3.jpg',
        image8: './assets/E4 opening/French Defense/Fwhitemv4.jpg',
        image9:  './assets/E4 opening/French Defense/Fblackmv4.jpg',
        image10: './assets/E4 opening/French Defense/Fwhitemv5.jpg',
        image11: './assets/E4 opening/French Defense/Fblackmv5.jpg',
        description2:'',
        image12: './assets/E4 opening/French Defense/Fblackmv5.jpg'
        
    },
    {
        name: 'Italian Game',
        description: ' ',
        image0: './assets/E4 opening/italian_game/IG_Wmv5.jpg',
        image1: './assets/E4 opening/italian_game/IG_starting position.jpg',
        image2: './assets/E4 opening/italian_game/IG_Wmv1.jpg',
        image3: './assets/E4 opening/italian_game/IG_Bmv1.jpg',
        image4: './assets/E4 opening/italian_game/IG_Wmv2.jpg',
        image5: './assets/E4 opening/italian_game/IG_Bmv2.jpg',
        image6: './assets/E4 opening/italian_game/IG_Wmv3.jpg',
        image7: './assets/E4 opening/italian_game/IG_Bmv3.jpg',
        image8: './assets/E4 opening/italian_game/IG_Wmv4.jpg',
        image9:  './assets/E4 opening/italian_game/IG_Bmv4.jpg',
        image10: './assets/E4 opening/italian_game/IG_Wmv5.jpg',
        image11: './assets/E4 opening/italian_game/IG_Wmv5.jpg',
        description2:'',
        image12: './assets/E4 opening/italian_game/IG_Wmv5.jpg'
        
    },
    {
        name: 'Kings Gambit',
        description: ' ',
        image0: './assets/E4 opening/kings Gambit/KG_Bmv5.jpg',
        image1: './assets/E4 opening/kings Gambit/KG_starting position.jpg',
        image2: './assets/E4 opening/kings Gambit/KG_Wmv1.jpg',
        image3: './assets/E4 opening/kings Gambit/KG_Bmv1.jpg',
        image4: './assets/E4 opening/kings Gambit/KG_Wmv2.jpg',
        image5: './assets/E4 opening/kings Gambit/KG_Bmv2.jpg',
        image6: './assets/E4 opening/kings Gambit/KG_Wmv3.jpg',
        image7: './assets/E4 opening/kings Gambit/KG_Bmv3.jpg',
        image8: './assets/E4 opening/kings Gambit/KG_Wmv4.jpg',
        image9:  './assets/E4 opening/kings Gambit/KG_Bmv4.jpg',
        image10: './assets/E4 opening/kings Gambit/KG_Wmv5.jpg',
        image11: './assets/E4 opening/kings Gambit/KG_Bmv5.jpg',
        description2:'',
        image12: './assets/E4 opening/kings Gambit/KG_Bmv5.jpg'
        
    },
    {
        name: 'Scoth Game',
        description: ' ',
        image0: './assets/E4 opening/scotch game/Scotch_Wmv5.jpg',
        image1: './assets/E4 opening/scotch game/Scotch_starting position.jpg',
        image2: './assets/E4 opening/scotch game/Scotch_Wmv1.jpg',
        image3: './assets/E4 opening/scotch game/Scotch_Bmv1.jpg',
        image4: './assets/E4 opening/scotch game/Scotch_Wmv2.jpg',
        image5: './assets/E4 opening/scotch game/Scotch_Bmv2.jpg',
        image6: './assets/E4 opening/scotch game/Scotch_Wmv3.jpg',
        image7: './assets/E4 opening/scotch game/Scotch_Bmv3.jpg',
        image8: './assets/E4 opening/scotch game/Scotch_Wmv4.jpg',
        image9:  './assets/E4 opening/scotch game/Scotch_Bmv4.jpg',
        image10: './assets/E4 opening/scotch game/Scotch_Wmv5.jpg',
        image11: './assets/E4 opening/scotch game/Scotch_Bmv5.jpg',
        description2:'',
        image12: './assets/E4 opening/scotch game/Scotch_Bmv5.jpg'
        
    },
    {
        name: 'The Scandivanian Defense',
        description: ' ',
        image0: './assets/E4 opening/the scandinavian defense/scand_black_mv5.jpg',
        image1: './assets/E4 opening/the scandinavian defense/scandinavian_starting_position.jpg',
        image2: './assets/E4 opening/the scandinavian defense/scand_White_mv1.jpg',
        image3: './assets/E4 opening/the scandinavian defense/scand_black_mv1.jpg',
        image4: './assets/E4 opening/the scandinavian defense/scand_White_mv2.jpg',
        image5: './assets/E4 opening/the scandinavian defense/scand_black_mv2.jpg',
        image6: './assets/E4 opening/the scandinavian defense/scand_White_mv3.jpg',
        image7: './assets/E4 opening/the scandinavian defense/scand_black_mv3.jpg',
        image8: './assets/E4 opening/the scandinavian defense/scand_White_mv4.jpg',
        image9:  './assets/E4 opening/the scandinavian defense/scand_black_mv4.jpg',
        image10: './assets/E4 opening/the scandinavian defense/scand_White_mv5.jpg',
        image11: './assets/E4 opening/the scandinavian defense/scand_black_mv5.jpg',
        description2:'',
        image12: './assets/E4 opening/the scandinavian defense/scand_black_mv5.jpg'
        
    },
    {
        name: 'The Sicilian Defense',
        description: ' ',
        image0: './assets/E4 opening/the sicilian defense/sicilian_blackmv5.jpg',
        image1: './assets/E4 opening/the sicilian defense/starting position.jpg',
        image2: './assets/E4 opening/the sicilian defense/sicilian_whitemv1.jpg',
        image3: './assets/E4 opening/the sicilian defense/sicilian_blackmv1.jpg',
        image4: './assets/E4 opening/the sicilian defense/sicilian_whitemv2.jpg',
        image5: './assets/E4 opening/the sicilian defense/sicilian_blackmv2.jpg',
        image6: './assets/E4 opening/the sicilian defense/sicilian_whitemv3.jpg',
        image7: './assets/E4 opening/the sicilian defense/sicilian_blackmv3.jpg',
        image8: './assets/E4 opening/the sicilian defense/sicilian_whitemv4.jpg',
        image9:  './assets/E4 opening/the sicilian defense/sicilian_blackmv4.jpg',
        image10: './assets/E4 opening/the sicilian defense/sicilian_whitemv5.jpg',
        image11: './assets/E4 opening/the sicilian defense/sicilian_blackmv5.jpg',
        description2:'',
        image12: './assets/E4 opening/the sicilian defense/sicilian_blackmv5.jpg'
        
    }

]