import { Opening } from "./opening"


export const OPENING: Opening[]=[
    {
        name: 'Alekhines',
        description: ' ',
        image0: './assets/E4 opening/alekhines_defense/alekhine_defense.jpg',
        image1: './assets/E4 opening/alekhines_defense/Alek_startingPosition.jpg',
        image2: './assets/E4 opening/alekhines_defense/Alek_Wmv1.jpg',
        image3: './assets/E4 opening/alekhines_defense/Alek_Bmv1.jpg',
        image4: './assets/E4 opening/alekhines_defense/Alek_Wmv2.jpg',
        image5: './assets/E4 opening/alekhines_defense/Alek_Bmv2.jpg',
        image6: './assets/E4 opening/alekhines_defense/Alek_Wmv3.jpg',
        image7: './assets/E4 opening/alekhines_defense/Alek_Bmv3.jpg',
        image8: './assets/E4 opening/alekhines_defense/Alek_Wmv4.jpg',
        image9: './assets/E4 opening/alekhines_defense/Alek_Bmv4.jpg',
        image10: './assets/E4 opening/alekhines_defense/Alek_Wmv5.jpg',
        image11: './assets/E4 opening/alekhines_defense/Alek_Bmv5.jpg',
        image12: './assets/E4 opening/alekhines_defense/alekhine_defense.jpg'
        
    },
    {
        name: 'Caro-kann',
        description: ' ',
        image0: './assets/E4 opening/caro-kann/ckblack_mv5.jpg',
        image1: './assets/E4 opening/Caro-kann/ckstartng_position.jpg',
        image2: './assets/E4 opening/Caro-kann/ckwhite_mv1.jpg',
        image3: './assets/E4 opening/Caro-kann/ckblack_mv1.jpg',
        image4: './assets/E4 opening/Caro-kann/ckwhite_mv2.jpg',
        image5: './assets/E4 opening/Caro-kann/ckblack_mv2.jpg',
        image6: './assets/E4 opening/Caro-kann/ckwhite_mv3.jpg',
        image7: './assets/E4 opening/Caro-kann/ckblack_mv3.jpg',
        image8: './assets/E4 opening/Caro-kann/ckwhite_mv4.jpg',
        image9:  './assets/E4 opening/Caro-kann/ckblack_mv4.jpg',
        image10: './assets/E4 opening/Caro-kann/ckwhite_mv5.jpg',
        image11: './assets/E4 opening/Caro-kann/ckblack_mv5.jpg',
        image12: './assets/E4 opening/Caro-kann/ckblack_mv5.jpg'
        
    },
    {
        name: 'French Defense',
        description: ' ',
        image0: './assets/E4 opening/french defense/Fblackmv5.jpg',
        image1: './assets/E4 opening/French Defense/fstartng_position.jpg',
        image2: './assets/E4 opening/French Defense/Fwhitemv1.jpg',
        image3: './assets/E4 opening/French Defense/Fblackmv1.jpg',
        image4: './assets/E4 opening/French Defense/Fwhitemv2.jpg',
        image5: './assets/E4 opening/French Defense/Fblackmv2.jpg',
        image6: './assets/E4 opening/French Defense/Fwhitemv3.jpg',
        image7: './assets/E4 opening/French Defense/Fblackmv3.jpg',
        image8: './assets/E4 opening/French Defense/Fwhitemv4.jpg',
        image9:  './assets/E4 opening/French Defense/Fblackmv4.jpg',
        image10: './assets/E4 opening/French Defense/Fwhitemv5.jpg',
        image11: './assets/E4 opening/French Defense/Fblackmv5.jpg',
        image12: './assets/E4 opening/French Defense/Fblackmv5.jpg'
        
    },
    {
        name: 'Italian Game',
        description: ' ',
        image0: './assets/E4 opening/italian_game/IG_Wmv5.jpg',
        image1: './assets/E4 opening/italian_game/IG_starting position.jpg',
        image2: './assets/E4 opening/italian_game/IG_Wmv1.jpg',
        image3: './assets/E4 opening/italian_game/IG_Bmv1.jpg',
        image4: './assets/E4 opening/italian_game/IG_Wmv2.jpg',
        image5: './assets/E4 opening/italian_game/IG_Bmv2.jpg',
        image6: './assets/E4 opening/italian_game/IG_Wmv3.jpg',
        image7: './assets/E4 opening/italian_game/IG_Bmv3.jpg',
        image8: './assets/E4 opening/italian_game/IG_Wmv4.jpg',
        image9:  './assets/E4 opening/italian_game/IG_Bmv4.jpg',
        image10: './assets/E4 opening/italian_game/IG_Wmv5.jpg',
        image11: './assets/E4 opening/italian_game/IG_Wmv5.jpg',
        image12: './assets/E4 opening/italian_game/IG_Wmv5.jpg'
        
    },
    {
        name: 'Kings Gambit',
        description: ' ',
        image0: './assets/E4 opening/kings Gambit/KG_Bmv5.jpg',
        image1: './assets/E4 opening/kings Gambit/KG_starting position.jpg',
        image2: './assets/E4 opening/kings Gambit/KG_Wmv1.jpg',
        image3: './assets/E4 opening/kings Gambit/KG_Bmv1.jpg',
        image4: './assets/E4 opening/kings Gambit/KG_Wmv2.jpg',
        image5: './assets/E4 opening/kings Gambit/KG_Bmv2.jpg',
        image6: './assets/E4 opening/kings Gambit/KG_Wmv3.jpg',
        image7: './assets/E4 opening/kings Gambit/KG_Bmv3.jpg',
        image8: './assets/E4 opening/kings Gambit/KG_Wmv4.jpg',
        image9:  './assets/E4 opening/kings Gambit/KG_Bmv4.jpg',
        image10: './assets/E4 opening/kings Gambit/KG_Wmv5.jpg',
        image11: './assets/E4 opening/kings Gambit/KG_Bmv5.jpg',
        image12: './assets/E4 opening/kings Gambit/KG_Bmv5.jpg'
        
    },
    {
        name: 'Scoth Game',
        description: ' ',
        image0: './assets/E4 opening/scotch game/Scotch_Wmv5.jpg',
        image1: './assets/E4 opening/scotch game/Scotch_starting position.jpg',
        image2: './assets/E4 opening/scotch game/Scotch_Wmv1.jpg',
        image3: './assets/E4 opening/scotch game/Scotch_Bmv1.jpg',
        image4: './assets/E4 opening/scotch game/Scotch_Wmv2.jpg',
        image5: './assets/E4 opening/scotch game/Scotch_Bmv2.jpg',
        image6: './assets/E4 opening/scotch game/Scotch_Wmv3.jpg',
        image7: './assets/E4 opening/scotch game/Scotch_Bmv3.jpg',
        image8: './assets/E4 opening/scotch game/Scotch_Wmv4.jpg',
        image9:  './assets/E4 opening/scotch game/Scotch_Bmv4.jpg',
        image10: './assets/E4 opening/scotch game/Scotch_Wmv5.jpg',
        image11: './assets/E4 opening/scotch game/Scotch_Bmv5.jpg',
        image12: './assets/E4 opening/scotch game/Scotch_Bmv5.jpg'
        
    },
    {
        name: 'The Scandivanian Defense',
        description: ' ',
        image0: './assets/E4 opening/the scandinavian defense/scand_black_mv5.jpg',
        image1: './assets/E4 opening/the scandinavian defense/scandinavian_starting_position.jpg',
        image2: './assets/E4 opening/the scandinavian defense/scand_White_mv1.jpg',
        image3: './assets/E4 opening/the scandinavian defense/scand_black_mv1.jpg',
        image4: './assets/E4 opening/the scandinavian defense/scand_White_mv2.jpg',
        image5: './assets/E4 opening/the scandinavian defense/scand_black_mv2.jpg',
        image6: './assets/E4 opening/the scandinavian defense/scand_White_mv3.jpg',
        image7: './assets/E4 opening/the scandinavian defense/scand_black_mv3.jpg',
        image8: './assets/E4 opening/the scandinavian defense/scand_White_mv4.jpg',
        image9:  './assets/E4 opening/the scandinavian defense/scand_black_mv4.jpg',
        image10: './assets/E4 opening/the scandinavian defense/scand_White_mv5.jpg',
        image11: './assets/E4 opening/the scandinavian defense/scand_black_mv5.jpg',
        image12: './assets/E4 opening/the scandinavian defense/scand_black_mv5.jpg'
        
    },
    {
        name: 'The Sicilian Defense',
        description: ' ',
        image0: './assets/E4 opening/the sicilian defense/sicilian_blackmv5.jpg',
        image1: './assets/E4 opening/the sicilian defense/starting position.jpg',
        image2: './assets/E4 opening/the sicilian defense/sicilian_whitemv1.jpg',
        image3: './assets/E4 opening/the sicilian defense/sicilian_blackmv1.jpg',
        image4: './assets/E4 opening/the sicilian defense/sicilian_whitemv2.jpg',
        image5: './assets/E4 opening/the sicilian defense/sicilian_blackmv2.jpg',
        image6: './assets/E4 opening/the sicilian defense/sicilian_whitemv3.jpg',
        image7: './assets/E4 opening/the sicilian defense/sicilian_blackmv3.jpg',
        image8: './assets/E4 opening/the sicilian defense/sicilian_whitemv4.jpg',
        image9:  './assets/E4 opening/the sicilian defense/sicilian_blackmv4.jpg',
        image10: './assets/E4 opening/the sicilian defense/sicilian_whitemv5.jpg',
        image11: './assets/E4 opening/the sicilian defense/sicilian_blackmv5.jpg',
        image12: './assets/E4 opening/the sicilian defense/sicilian_blackmv5.jpg'
        
    },
    {
        name: 'Catalan',
        description: ' ',
        image0: './assets/d4_openings/catalanOpening/catalan_Wmv6.jpg',
        image1: './assets/d4_openings/catalanOpening/catalan_starting position.jpg',
        image2: './assets/d4_openings/catalanOpening/catalan_Wmv1.jpg',
        image3: './assets/d4_openings/catalanOpening/catalan_Bmv1.jpg',
        image4: './assets/d4_openings/catalanOpening/catalan_Wmv2.jpg',
        image5: './assets/d4_openings/catalanOpening/catalan_Bmv2.jpg',
        image6: './assets/d4_openings/catalanOpening/catalan_Wmv3.jpg',
        image7: './assets/d4_openings/catalanOpening/catalan_Bmv3.jpg',
        image8: './assets/d4_openings/catalanOpening/catalan_Wmv4.jpg',
        image9:  './assets/d4_openings/catalanOpening/catalan_Bmv4.jpg',
        image10: './assets/d4_openings/catalanOpening/catalan_Wmv5.jpg',
        image11: './assets/d4_openings/catalanOpening/catalan_Bmv5.jpg',
        image12: './assets/d4_openings/catalanOpening/catalan_Wmv6.jpg'
        
    },
    {
        name: 'Dutch Defense',
        description: ' ',
        image0: './assets/d4_openings/dutch_defense/dutch_BMv5.jpg',
        image1: './assets/d4_openings/dutch_defense/dutch_starting position.jpg',
        image2: './assets/d4_openings/dutch_defense/dutch_Mv1.jpg',
        image3: './assets/d4_openings/dutch_defense/dutch_BMv1.jpg',
        image4: './assets/d4_openings/dutch_defense/dutch_Wmv2.jpg',
        image5: './assets/d4_openings/dutch_defense/dutch_BMv2.jpg',
        image6: './assets/d4_openings/dutch_defense/dutch_Wmv3.jpg',
        image7: './assets/d4_openings/dutch_defense/dutch_BMv3.jpg',
        image8: './assets/d4_openings/dutch_defense/dutch_Wmv4.jpg',
        image9:  './assets/d4_openings/dutch_defense/dutch_BMv4.jpg',
        image10: './assets/d4_openings/dutch_defense/dutch_Wmv5.jpg',
        image11: './assets/d4_openings/dutch_defense/dutch_BMv5.jpg',
        image12: './assets/d4_openings/dutch_defense/dutch_BMv5.jpg'
        
    },
    {
        name: 'London System',
        description: ' ',
        image0: './assets/d4_openings/london_system/Lblack_mv5.jpg',
        image1: './assets/d4_openings/london_system/london_starting position.jpg',
        image2: './assets/d4_openings/london_system/Lwhite_mv1.jpg',
        image3: './assets/d4_openings/london_system/Lblack_mv1.jpg',
        image4: './assets/d4_openings/london_system/Lwhite_mv2.jpg',
        image5: './assets/d4_openings/london_system/Lblack_mv2.jpg',
        image6: './assets/d4_openings/london_system/Lwhite_mv3.jpg',
        image7: './assets/d4_openings/london_system/Lblack_mv3.jpg',
        image8: './assets/d4_openings/london_system/Lwhite_mv4.jpg',
        image9:  './assets/d4_openings/london_system/Lblack_mv4.jpg',
        image10: './assets/d4_openings/london_system/Lwhite_mv5.jpg',
        image11: './assets/d4_openings/london_system/Lblack_mv5.jpg',
        image12: './assets/d4_openings/london_system/Lblack_mv5.jpg'
        
    },
    {
        name: 'Queens Indian Defense',
        description: ' ',
        image0: './assets/d4_openings/QueensIndian_Defense/QI_Wm6.jpg',
        image1: './assets/d4_openings/QueensIndian_Defense/QI_starting position.jpg',
        image2: './assets/d4_openings/QueensIndian_Defense/QI_Wm1.jpg',
        image3: './assets/d4_openings/QueensIndian_Defense/QI_Bm1.jpg',
        image4: './assets/d4_openings/QueensIndian_Defense/QI_Wm2.jpg',
        image5: './assets/d4_openings/QueensIndian_Defense/QI_Bm2.jpg',
        image6: './assets/d4_openings/QueensIndian_Defense/QI_Wm3.jpg',
        image7: './assets/d4_openings/QueensIndian_Defense/QI_Bm3.jpg',
        image8: './assets/d4_openings/QueensIndian_Defense/QI_Wm4.jpg',
        image9:  './assets/d4_openings/QueensIndian_Defense/QI_Bm4.jpg',
        image10: './assets/d4_openings/QueensIndian_Defense/QI_Wm5.jpg',
        image11: './assets/d4_openings/QueensIndian_Defense/QI_Bm5.jpg',
        image12: './assets/d4_openings/QueensIndian_Defense/QI_Wm6.jpg'
        
    },
    {
        name: 'The Slav Defense',
        description: ' ',
        image0: './assets/d4_openings/the slav defense/slav_black_mv5.jpg',
        image1: './assets/d4_openings/the slav defense/slav_starting_position.jpg',
        image2: './assets/d4_openings/the slav defense/slav_WE4_mv1.jpg',
        image3: './assets/d4_openings/the slav defense/slav_BD5_mv1.jpg',
        image4: './assets/d4_openings/the slav defense/slav_WC4_mv2.jpg',
        image5: './assets/d4_openings/the slav defense/slav_BC6_mv2.jpg',
        image6: './assets/d4_openings/the slav defense/slav_White_mv3.jpg',
        image7: './assets/d4_openings/the slav defense/slav_black_mv3.jpg',
        image8: './assets/d4_openings/the slav defense/slav_White_mv4.jpg',
        image9:  './assets/d4_openings/the slav defense/slav_black_mv4.jpg',
        image10: './assets/d4_openings/the slav defense/slav_White_mv5.jpg',
        image11: './assets/d4_openings/the slav defense/slav_black_mv5.jpg',
        image12: './assets/d4_openings/the slav defense/slav_black_mv5.jpg'
        
    },
    {
        name: 'The Queens Gambit',
        description: ' ',
        image0: './assets/d4_openings/the_queens_gambit/QG_white_mv5_options.jpg',
        image1: './assets/d4_openings/the_queens_gambit/QG_starting_position.jpg',
        image2: './assets/d4_openings/the_queens_gambit/QG_white_mv1.jpg',
        image3: './assets/d4_openings/the_queens_gambit/QG_black_mv1.jpg',
        image4: './assets/d4_openings/the_queens_gambit/QG_white_mv2.jpg',
        image5: './assets/d4_openings/the_queens_gambit/QG_black_mv2.jpg',
        image6: './assets/d4_openings/the_queens_gambit/QG_white_mv3.jpg',
        image7: './assets/d4_openings/the_queens_gambit/QG_black_mv3.jpg',
        image8: './assets/d4_openings/the_queens_gambit/QG_white_mv4.jpg',
        image9:  './assets/d4_openings/the_queens_gambit/QG_black_mv3_option2.jpg',
        image10: './assets/d4_openings/the_queens_gambit/QG_white_mv5_options.jpg',
        image11: './assets/d4_openings/the_queens_gambit/QG_white_mv5_options.jpg',
        image12: './assets/d4_openings/the_queens_gambit/QG_white_mv5_options.jpg'
        
    },
    {
        name: 'English',
        description: ' ',
        image0: './assets/other/engishOpening/english_WBmv6.jpg',
        image1: './assets/other/engishOpening/english_starting position.jpg',
        image2: './assets/other/engishOpening/english_Wmv1.jpg',
        image3: './assets/other/engishOpening/english_Bmv1.jpg',
        image4: './assets/other/engishOpening/english_Wmv2.jpg',
        image5: './assets/other/engishOpening/english_Bmv2.jpg',
        image6: './assets/other/engishOpening/english_Wmv3.jpg',
        image7: './assets/other/engishOpening/english_bmv3.jpg',
        image8: './assets/other/engishOpening/english_Wmv4.jpg',
        image9:  './assets/other/engishOpening/english_Bmv4.jpg',
        image10: './assets/other/engishOpening/english_Wmv5.jpg',
        image11: './assets/other/engishOpening/english_Bmv5.jpg',
        image12: './assets/other/engishOpening/english_WBmv6.jpg'
        
    },
    {
        name: 'Fianchetto',
        description: ' ',
        image0: './assets/other/fianchetto_Opening/fian_Wbmv6.jpg',
        image1: './assets/other/fianchetto_Opening/fian_starting position.jpg',
        image2: './assets/other/fianchetto_Opening/fian_Wmv1.jpg',
        image3: './assets/other/fianchetto_Opening/fian_Bmv1.jpg',
        image4: './assets/other/fianchetto_Opening/fian_Wmv2.jpg',
        image5: './assets/other/fianchetto_Opening/fian_Bmv2.jpg',
        image6: './assets/other/fianchetto_Opening/fian_Wmv3.jpg',
        image7: './assets/other/fianchetto_Opening/fian_Bmv3.jpg',
        image8: './assets/other/fianchetto_Opening/fian_Wmv4.jpg',
        image9:  './assets/other/fianchetto_Opening/fian_Bmv4.jpg',
        image10: './assets/other/fianchetto_Opening/fian_Wmv5.jpg',
        image11: './assets/other/fianchetto_Opening/fian_Bmv5.jpg',
        image12: './assets/other/fianchetto_Opening/fian_Wbmv6.jpg'
        
    },
    {
        name: 'Nimzoswitch-larsen',
        description: ' ',
        image0: './assets/other/nimzoswitch-larsen_attack/nimzo_Wmv6.jpg',
        image1: './assets/other/nimzoswitch-larsen_attack/nimzo_starting position.jpg',
        image2: './assets/other/nimzoswitch-larsen_attack/nimzo_Wmv1.jpg',
        image3: './assets/other/nimzoswitch-larsen_attack/nimzo_Bmv1.jpg',
        image4: './assets/other/nimzoswitch-larsen_attack/nimzo_Wmv2.jpg',
        image5: './assets/other/nimzoswitch-larsen_attack/nimzo_Bmv2.jpg',
        image6: './assets/other/nimzoswitch-larsen_attack/nimzo_Wmv3.jpg',
        image7: './assets/other/nimzoswitch-larsen_attack/nimzo_Bmv3.jpg',
        image8: './assets/other/nimzoswitch-larsen_attack/nimzo_Wmv4.jpg',
        image9:  './assets/other/nimzoswitch-larsen_attack/nimzo_Bmv4.jpg',
        image10: './assets/other/nimzoswitch-larsen_attack/nimzo_Wmv5.jpg',
        image11: './assets/other/nimzoswitch-larsen_attack/nimzo_Bmv5.jpg',
        image12: './assets/other/nimzoswitch-larsen_attack/nimzo_Wmv6.jpg'
        
    },
    {
        name: 'The Kings Indian Attack',
        description: ' ',
        image0: './assets/other/the_kingsIndian_attack/KIA_black_mv5.jpg',
        image1: './assets/other/the_kingsIndian_attack/KIA_starting_position.jpg',
        image2: './assets/other/the_kingsIndian_attack/KIA_White_mv1.jpg',
        image3: './assets/other/the_kingsIndian_attack/KIA_black_mv1.jpg',
        image4: './assets/other/the_kingsIndian_attack/KIA_White_mv2.jpg',
        image5: './assets/other/the_kingsIndian_attack/KIA_black_mv2.jpg',
        image6: './assets/other/the_kingsIndian_attack/KIA_White_mv3.jpg',
        image7: './assets/other/the_kingsIndian_attack/KIA_black_mv3.jpg',
        image8: './assets/other/the_kingsIndian_attack/KIA_White_mv4.jpg',
        image9:  './assets/other/the_kingsIndian_attack/KIA_black_mv4.jpg',
        image10: './assets/other/the_kingsIndian_attack/KIA_White_mv5.jpg',
        image11: './assets/other/the_kingsIndian_attack/KIA_black_mv5.jpg',
        image12: './assets/other/the_kingsIndian_attack/KIA_black_mv5.jpg'
        
    }

]